### ISSUE TITLE
Not Working on TShock 5.2 for Terraria 1.4.4.9

### ISSUE THREAD

**Issue by PLGC-AK47** [Zaicon/InfiniteChestsV3#24]
Keep getting this error. Sorry, don't know much about all of this. 

[Server API] Error InfiniteChestsV3.dll was built for X86 but expected it to be compatible with X64.
[Server API] Error Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Failed to load assembly "InfiniteChestsV3.dll".
 ---> System.IO.FileLoadException: Could not load file or assembly 'InfiniteChestsV3, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols)
   at System.Reflection.Assembly.Load(Byte[] rawAssembly, Byte[] rawSymbolStore)
   at TerrariaApi.Server.ServerApi.LoadPlugins() in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs:line 351
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins() in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs:line 422
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game) in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs:line 126
   at TerrariaApi.Server.HookManager.InitialiseAPI() in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/HookManager.cs:line 29

**Comment by SavageTheUnicorn** [comment]
Same here, but it's due to having Arm64 architecture for your cpu. Maybe the dev will come back and make an arm version lol
